#Flask应用配置
app:
  name: "DigitalElf"
  version: "1.0.0"
  debug: true
  host: "0.0.0.0"
  port: 5000
#WebSocket配置
ws:
  host: "0.0.0.0"
  port: 8765
#语音转文字FunASR配置
asr:
  model: "iic/SenseVoiceSmall"
  vad_model: "fsmn-vad"
  vad_kwargs:
    #最大语音段时间，单位毫秒，超过该时间将被切分为多个段进行处理
    max_single_segment_time: 30000
  device: "cuda"
  language: "auto"
  use_itn: true
  batch_size_s: 60
  merge_vad: true
  merge_length_s: 15
#rag配置
rag:
  #分片大小，单位为token，过大可能导致内存不足，过小可能导致上下文不连贯
  chunk_size: 200
  #分片重叠大小，单位为token，过大可能导致冗余信息过多，过小可能导致上下文丢失
  chunk_overlap: 50
  #embedding模型配置，建议选择支持多语言的模型，以便处理不同语言的文本数据
  model_name: "BAAI/bge-small-zh-v1.5"
#大模型配置
llm:
  model: "deepseek-chat"
  temperature: 0.7
  base_url: "https://api.deepseek.com/v1"
  stream: True
#情绪分类器小模型配置
emotion:
  task: "text-classification"
  model: 'bhadresh-savani/distilbert-base-uncased-emotion'
  return_all_scores: True
#tts配置
tts:
  url: "http://127.0.0.1:9880/tts"
  text_lang: "ja"
  ref_audio_path: "ref_audio.wav"
  prompt_text: "どうして私前にあなたと会ったことありますか"
  prompt_lang: "ja"
  streaming_mode: true
  media_type: "wav"
  timeout: 30
  chunk_size: 2048
#提示词配置
prompt:
  kurisu: "1.你是‘命运石之门’里面的角色牧濑红莉栖，严格按照游戏内的剧情进行2.不要用()来表述动作和内心的想法3.默认用日文来回答 "


